import FrontTemplate from '../components/FrontTemplate/FrontTemplate'
import Header from '../components/Header/Header'
import styles from '../styles/About.module.scss'
import CircleImageWithDot from '../components/CircleImageWithDot/CircleImageWithDot'
import {FaPlay}  from 'react-icons/fa'
import {IoMdPause} from 'react-icons/io'
import { BiMessageSquareAdd } from 'react-icons/bi'
import { useState ,useRef } from 'react'
import Image from 'next/image'
import Head from 'next/head'
import personImg from '../public/travel_51.jpg'
import TestMonails from '../components/home/testimonalis/TestIMonails'
import Footer from '../components/home/footer/Footer'
function About() {
    const [playing,setPlaying] = useState(false)
    const video = useRef(null)
    const teamMember = [
        {
            name: "Darrell",
            lastname : "Steward",
            image: personImg,
            information:'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.'
        },
        {
            name: "Wade",
            lastname : "Warren",
            image: personImg,
            information:'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.'
        },
        {
            name: "Kristin",
            lastname : "Watson",
            image: personImg,
            information:'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.'
        }
    ]
    const setPlayingState =() =>{
      
        if(video){
            if(playing){
                video.current.pause();
            }else{

                video.current.play();
            }
            setPlaying(!playing)
        }
    }
    return (
        <div className="">
              <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
           <Header/>
           <FrontTemplate title="Know About Us" subtitle="About Real Rodies"/>
           <div className={` is-flex  ${styles.ourVision}`}>
               <div className={`  ${styles.aboutLeft}`}>
                  <div className={`is-flex is-justify-content-end is-flex-direction-column is-align-content-end is-align-items-flex-end	`}>
                  <p className="is-size-2 is-size-3-mobile has-text-black">Our Vision</p>
     <p className="is-size-6 pt-5 pb-5 has-text-grey">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.</p>
               <div className="is-flex is-justify-content-flex-start is-align-items-center mr-auto">
               <CircleImageWithDot diameter={120}/>
               <div className="is-family-primary has-text-centered mt-5 pl-5">
                           <p className="is-size-7-mobile has-text-centered is-uppercase has-text-black has-text-weight-medium">Company name</p>
                           <p className="is-size-7-mobile is-capitalized has-text-weight-medium">lane lauren</p>
                           <p className="is-size-7-mobile is-uppercase has-text-weight-medium">ceo</p>
                   </div>
                
               </div>
              
                  </div>
               </div>
               <div className={`${styles.aboutRight}`}>
                       <div > 
                           <video ref={video}  autoPlay={false} src="https://cdn.videvo.net/videvo_files/video/free/2015-03/small_watermarked/BirdNoSound_preview.webm">
                             </video>
                           <div onClick={setPlayingState} className={ `${styles.playButton}`}>
                           
                            {
                                playing ? (
<IoMdPause className={`${styles.play}`}/>
                                ) : (
                                    <FaPlay className={`${styles.play}`}/>
                                )
                            }
                           </div>
                         
                       </div>
               </div>
           </div>
           <div className={styles.ourTeamMemberSection}>
               <p className="is-size-3 is-size-4 has-text-weight-bold mb-6 ml-5">Our Team</p>
               <div className={` is-flex  is-justify-content-space-between is-align-items-center ${styles.teamMembers}`}>
                   {
                       teamMember.map((team,index) => (
                          <>
                           <div key={index} className={`card is-flex ${styles.teamInfoCard}`}>
                       <Image className={`${styles.teamImage}`} src={team.image} alt="" width={80} height={80}/>
                        <div className="ml-3">
                            <p className="is-size-7">CEO</p>
                            <p className="is-size-5 has-text-weight-bold">{team.name}</p>
                            <p className="is-size-5 has-text-weight-bold">{team.lastname}</p>
                        </div>
                        
                      <BiMessageSquareAdd className={styles.teamCardMessage} />
                        {/* <div>
                            <p>{team.information}</p>
                        </div> */}
                    </div>
                          </> 
                       ))
                   }
                   
               </div>
           </div>
<TestMonails/>
<Footer/>
        </div>
    )
}

export default About
