import FrontTemplate from '../components/FrontTemplate/FrontTemplate'
import Header from '../components/Header/Header'
import styles from '../styles/Contact.module.scss'
import Head from 'next/head'
import Image from 'next/image'
import personImg from '../public/travel_51.jpg'
import Footer from '../components/home/footer/Footer'
import MyContact from '../components/home/contact/Contact'
function Contact() {
   
    return (
        <div className={styles.contactBody}>
              <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
           <Header/>
           <FrontTemplate title="Reach Out To Us" subtitle="Contact Us"/>
          <div className={styles.contactBodyImage}>

<Image className={styles.contact} src={personImg} alt="" width={430} height={300}/>
          </div>
<MyContact/>
<Footer/>
        </div>
    )
}

export default Contact
