import Head from 'next/head'
import MyHome from '../components/home/home'
import styles from '../styles/Home.module.scss'
import Header from '../components/Header/Header'


export default function Home() {
  
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Real Rodies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <div >
          
             <Header />
            
             <MyHome/>
          </div>
      </main>

     
    </div>
  )
}
