import FrontTemplate from "../components/FrontTemplate/FrontTemplate";
import Header from "../components/Header/Header";
import PackageCard from "../components/packages/card/Card";
import tripPhoto from "../public/travel_51.jpg";
import Footer from '../components/home/footer/Footer'
import styles from '../styles/Package.module.scss'
import Head from 'next/head'
function Packages() {
  const packages = [
    {
      imageSrc: tripPhoto,

      info: "2 Nights/3 Days",
      place: "Tirupati(2)",
      title: "trpupati balaji self drive tour",
      validDate: "09 Aug 2021 - 31 Mar 2022",
      price:'20204'
    },
    {
      imageSrc: tripPhoto,

      info: "2 Nights/3 Days",
      place: "Tirupati(2)",
      title: "trpupati balaji self drive tour",
      validDate: "09 Aug 2021 - 31 Mar 2022",
      price:'20204'
    },
    {
      imageSrc: tripPhoto,

      info: "2 Nights/3 Days",
      place: "Tirupati(2)",
      title: "trpupati balaji self drive tour",
      validDate: "09 Aug 2021 - 31 Mar 2022",
      price:'20204'
    },
    {
      imageSrc: tripPhoto,

      info: "2 Nights/3 Days",
      place: "Tirupati(2)",
      title: "trpupati balaji self drive tour",
      validDate: "09 Aug 2021 - 31 Mar 2022",
      price:'20204'
    },
    {
      imageSrc: tripPhoto,

      info: "2 Nights/3 Days",
      place: "Tirupati(2)",
      title: "trpupati balaji self drive tour",
      validDate: "09 Aug 2021 - 31 Mar 2022",
      price:'20204'
    },
    {
      imageSrc: tripPhoto,

      info: "2 Nights/3 Days",
      place: "Tirupati(2)",
      title: "trpupati balaji self drive tour",
      validDate: "09 Aug 2021 - 31 Mar 2022",
      price:'20204'
    },
  
  ];
  return (
    <div>
        <Head>
        <title>Package</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <FrontTemplate title="Know About Us" subtitle="About Real Rodies" />
      <div className={`is-flex is-flex-wrap-wrap is-justify-content-center is-align-items-center ${styles.showAllPackages}`}>
        {
            packages.map((trippackage,index) => (
                <PackageCard
                key={index}
                ImageSrc={trippackage.imageSrc}
                info={trippackage.info}
                place={trippackage.place}
                title={trippackage.title}
                validDate={trippackage.validDate}
                price={trippackage.price}
              />
            ))
        }
      </div>
      <Footer/>
    </div>
  );
}

export default Packages;
